%Find the volume of the solid generated by revolving
% about the x-axis the region bounded by the curve y = 4/((x^2)+4), 
% the x-axis, and the lines x = 0, x = 2.

clear all
clc
syms x
f(x) = 4/((x^2)+4);
yr = 0; % Axis of revolution y = 0
I = [0,2]; % Interval of integration between x=0 and x=2
a = I(1); b=I(2);
vol = pi*int((f(x)-yr)^2,a,b);
disp('Volume of solid of revolution is: ');
disp(vol);

% Visualization of solid of revolution
fx = matlabFunction(f);
xv = linspace(a,b,101); % Creates 101 points from a to b
[X,Y,Z] = cylinder(fx(xv)-yr);
Z = a+Z.*(b-a); 

surf(Z,Y+yr,X) % Plotting the solid of revolution about y = yr (X-AXIS)
hold on;
plot([a b],[yr yr],'-r','LineWidth',2); % Plotting the line y=yr
view(22,11); % 3-D graph viewpoint specification
xlabel('X-axis');ylabel('Y-axis');zlabel('Z-axis'); 